Updated

diff --git a/alienvault-api/alienvault-api/debian/alienvault-api.init b/alienvault-api/alienvault-api/debian/alienvault-api.init
--- a/alienvault-api/alienvault-api/debian/alienvault-api.init
+++ b/alienvault-api/alienvault-api/debian/alienvault-api.init
@@ -1,10 +1,10 @@
-#! /bin/sh
+#!/bin/sh
 ### BEGIN INIT INFO
 # Provides:          alienvault-api
-# Required-Start:    $remote_fs $syslog
-# Required-Stop:     $remote_fs $syslog
-# Should-Start:      rabbitmq-server mysql
-# Should-Stop:       rabbitmq-server mysql
+# Required-Start:    $remote_fs $syslog rabbitmq-server redis-server alienvault-redis-server-otx
+# Required-Stop:     $remote_fs $syslog rabbitmq-server redis-server alienvault-redis-server-otx
+# Should-Start:      mysql ossim-server ossim-agent
+# Should-Stop:       mysql ossim-server ossim-agent
 # Default-Start:     2 3 4 5
 # Default-Stop:      0 1 6
 # Short-Description: AlienVault API init script
@@ -20,18 +20,39 @@
 NAME=api
 DESC="AlienVault API"
 
-CELERYD="/usr/share/alienvault/api/scripts/venv_celeryd.sh"
-CELERYBEAT="/usr/share/alienvault/api/scripts/venv_celerybeat.sh"
+CELERYD="/usr/share/python/alienvault-api/scripts/venv_celeryd.sh"
+CELERYBEAT="/usr/share/python/alienvault-api/scripts/venv_celerybeat.sh"
+
+#
+# Function to cleanup rabbit queues.
+#
+cleanup_rabbit_queues() {
+  log_daemon_msg "Clean up rabbit queues"
+  rabbitmqctl stop_app > /dev/null 2>&1
+  rabbitmqctl reset > /dev/null 2>&1
+  rabbitmqctl start_app > /dev/null 2>&1
+}
+
 
 #
 # Function that starts the daemon/service
 #
 do_start() {
+  # We don't want to process old tasks, so reset our rabbitapp.
+  cleanup_rabbit_queues
+
+  if [ -d "/var/log/alienvault/api" ]; then
+      chown avapi:alienvault /var/log/alienvault/api -R
+      for logfile in /var/log/alienvault/api/*; do chmod 644 $logfile; done
+  fi
+
   log_daemon_msg "Starting CeleryBeat" "celerybeat"
-  ($CELERYBEAT start > /dev/null 2>&1 && log_success_msg) || (log_failure_msg && return $?)
+  start-stop-daemon --quiet --start --exec $CELERYBEAT start
+  # ($CELERYBEAT start > /dev/null 2>&1 && log_success_msg) || (log_failure_msg && return $?)
 
   log_daemon_msg "Starting CeleryD" "celeryd"
-  ($CELERYD start > /dev/null 2>&1 && log_success_msg) || (log_failure_msg && return $?)
+  start-stop-daemon --quiet --start --exec $CELERYD start
+  # ($CELERYD start > /dev/null 2>&1 && log_success_msg) || (log_failure_msg && return $?)
 }
 
 #
@@ -46,11 +67,11 @@ do_stop() {
 
   # Just try to kill stunnel4
 
-  log_daemon_msg "Stopping CeleryBeat" "celerybeat"
-  ($CELERYBEAT stop > /dev/null 2>&1 && log_success_msg) || (log_failure_msg && return $?)
-
   log_daemon_msg "Stopping CeleryD" "celeryd"
   ($CELERYD stop > /dev/null 2>&1 && log_success_msg) || (log_failure_msg && return $?)
+  kill -9 `ps aux|grep celery.bin.celeryd | awk '{print $2}'`  > /dev/null 2>&1 || true
+  log_daemon_msg "Stopping CeleryBeat" "celerybeat"
+  ($CELERYBEAT stop > /dev/null 2>&1 && log_success_msg) || (log_failure_msg && return $?)
 
   return 0
 }
@@ -78,7 +99,7 @@ case "$1" in
     1) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
   esac
   ;;
-  restart)
+  restart|force-reload)
   log_daemon_msg "Restarting $DESC" "$NAME"
   log_success_msg
   do_stop
@@ -107,11 +128,11 @@ case "$1" in
   esac
   ;;
   *)
-  echo "Usage: $SCRIPTNAME {start|stop|restart|reload}" >&2
+  echo "Usage: $SCRIPTNAME {start|stop|restart|reload|force-reload}" >&2
   ;;
 esac
 
-if [ -e /proc/$$/fd/3 ]; then
-    echo STOP  2>&1 >/dev/null  >&3 || /bin/true
-fi
+#if [ -e /proc/$$/fd/3 ]; then
+#    echo STOP  2>&1 >/dev/null  >&3 || /bin/true
+#fi
 exit 0
diff --git a/alienvault-api/alienvault-api/debian/alienvault-api.postinst b/alienvault-api/alienvault-api/debian/alienvault-api.postinst
--- a/alienvault-api/alienvault-api/debian/alienvault-api.postinst
+++ b/alienvault-api/alienvault-api/debian/alienvault-api.postinst
@@ -1,36 +1,111 @@
-#!/bin/bash
+#!/bin/sh
+# postinst script for alienvault-api
+#
+# see: dh_installdeb(1)
 
-#set -e
+set -e
 
-. /usr/share/debconf/confmodule
+# summary of how this script can be called:
+#        * <postinst> `configure' <most-recently-configured-version>
+#        * <old-postinst> `abort-upgrade' <new version>
+#        * <conflictor's-postinst> `abort-remove' `in-favour' <package>
+#          <new-version>
+#        * <postinst> `abort-remove'
+#        * <deconfigured's-postinst> `abort-deconfigure' `in-favour'
+#          <failed-install-package> <version> `removing'
+#          <conflicting-package> <version>
+# for details, see http://www.debian.org/doc/debian-policy/ or
+# the debian-policy package
 
-if [ "$OSSIM_DEBUG" = "TRUE" ];then
-   set -x
-fi
+case "$1" in
+    configure)
+        # Check for api user & group, just in case...
+        if ! getent group alienvault > /dev/null; then
+	        addgroup --quiet --system alienvault
+        fi
+        if ! getent passwd avapi > /dev/null; then
+	        adduser  --home /home/avapi  --system --shell /bin/bash --ingroup alienvault --gecos "AlienVault SIEM" avapi
+        fi
+        if [ ! -d /home/avapi/.ssh ]
+        then
+	        mkdir /home/avapi/.ssh
+	        chmod 0750 /home/avapi/.ssh
+	        chown avapi:alienvault  /home/avapi/.ssh
+        fi
+        if [ -f /home/avapi/.ssh/known_hosts ]
+        then
+            ssh-keygen -R 127.0.0.1 -f /home/avapi/.ssh/known_hosts
+            ssh-keygen -R localhost -f /home/avapi/.ssh/known_hosts
+        fi
+        ssh-keyscan 127.0.0.1 localhost >> /home/avapi/.ssh/known_hosts
+        chown avapi:alienvault /home/avapi/.ssh/known_hosts
+        chmod 600  /home/avapi/.ssh/known_hosts
+        chown -f avapi:alienvault /home/avapi/.ssh/known_hosts.old || true
 
-# Check for api user & group, just in case...
-if ! getent group alienvault > /dev/null; then
-	addgroup --quiet --system alienvault
-fi
-if ! getent passwd avapi > /dev/null; then
-	adduser --system --shell /bin/bash --ingroup alienvault --gecos "AlienVault SIEM" avapi
-fi
+        # Check for permissions in /etc/ossim.
+        [ -d /etc/ossim ] || exit -1
+        chgrp alienvault /etc/ossim -R
 
-# Check for permissions in /etc/ossim.
-[ -d /etc/ossim ] || exit -1
-chgrp alienvault /etc/ossim -R
+        # Check for permissions in /etc/alienvault/api
+        [ -d /etc/alienvault/api ] || exit -1
+        chown -R avapi:alienvault /etc/alienvault/api/
+        chmod -R 0770 /etc/alienvault/api
 
-# Add the listen port 40011 to /etc/apache2/ports.conf
-grep --fixed-strings --quiet "Listen 40011" /etc/apache2/ports.conf || echo "Listen 40011"  >> /etc/apache2/ports.conf
+        # Add the listen port 40011 to /etc/apache2/ports.conf
+        grep --fixed-strings --quiet "Listen 40011" /etc/apache2/ports.conf || echo "Listen 40011"  >> /etc/apache2/ports.conf
 
-# Create secret key
-if [ ! -f /usr/share/alienvault/api/secret.py ]
-then
-    echo "key = '$(pwgen -s 24)'" > /usr/share/alienvault/api/secret.py
-fi
+        # Create secret key
+        if [ ! -f /usr/share/python/alienvault-api/secret.py ]
+        then
+            echo "key = '$(pwgen -s 24)'" > /usr/share/python/alienvault-api/secret.py
+        fi
+
+        # Fix a condition specific to versions < 4.12.0
+        if [ ! -z "$2" ]; then
+            if dpkg --compare-versions "$2" le "4.12.0"; then
+                kill -9 `pgrep -f celeryd`  > /dev/null 2>&1 || true
+                kill -9 `pgrep -f celerybeat`  > /dev/null 2>&1 || true
+            fi
+        fi
+
+        # Set scripts as executables.
+        if [ -d "/usr/share/python/alienvault-api/scripts/" ]; then
+            chown avapi:alienvault /usr/share/python/alienvault-api/scripts/*
+            chmod 770 /usr/share/python/alienvault-api/scripts/*
+        fi
+
+        # Enable the apache2 configuration.
+        if [ -x "/usr/sbin/a2ensite" ]; then
+           a2ensite alienvault-api.conf
+        fi
+    ;;
+
+    triggered)
+        for trigger in $2
+        do
+            case "$trigger" in
+                alienvault-restart-apache2)
+                ;;
+                *)
+                    echo "postinst called with unknown trigger \`$2'">&2
+                    exit 1
+                ;;
+            esac
+        done
+    ;;
+
+    abort-upgrade|abort-remove|abort-deconfigure)
+    ;;
+
+    *)
+        echo "postinst called with unknown argument \`$1'" >&2
+        exit 1
+    ;;
+esac
+
+# dh_installdeb will replace this with shell code automatically
+# generated by other debhelper scripts.
 
 #DEBHELPER#
-
-db_stop
 
 exit 0
diff --git a/alienvault-dummies-config/debian/alienvault-firewall.postinst b/alienvault-dummies-config/debian/alienvault-firewall.postinst
--- a/alienvault-dummies-config/debian/alienvault-firewall.postinst
+++ b/alienvault-dummies-config/debian/alienvault-firewall.postinst
@@ -16,44 +16,62 @@ set -e
 #          <conflicting-package> <version>
 # for details, see http://www.debian.org/doc/debian-policy/ or
 # the debian-policy package
-DEPRECATED_FIREWALL_FILE="/etc/ossim_firewall"
-DEPRECATED_FIREWALL_IP6_FILE="/etc/ossim_firewall_ipv6"
-BACKUP_DEPRECATED_FIREWALL_FILE="/etc/ossim_firewall.dpkg-old"
-BACKUP_DEPRECATED_FIREWALL_IP6_FILE="/etc/ossim_firewall_ipv6.dpkg-old"
 CUSTOM_FIREWALL_RULES="/etc/ossim/firewall_include"
 TMP_FIREWALL_CUSTOM_RULES="/tmp/av_include_iptables.tmp"
 TMP_TEST_RULES_RESULT="/tmp/ofv.tmp"
 VALID_FIREWALL_CUSTOM_RULES="/etc/iptables/rules012-custom.iptables"
 DEPRECATED_FIREWALL_RULES="/etc/ossim_firewall"
 DEPRECATED_FIREWALL_IP6_RULES="/etc/ossim_firewall_ipv6"
+
+LAST_INPUT_RULES="-A INPUT -p ICMP --icmp-type timestamp-request -j DROP
+-A INPUT -p icmp -j ACCEPT
+-A INPUT -j REJECT --reject-with icmp-host-prohibited"
+LAST_OUTPUT_RULE="-A OUTPUT -p ICMP --icmp-type timestamp-reply -j DROP"
  
 configure_firewall(){
     # Prepares the custom rules added by the user in the firewall_include file
     # to make them be applied in the firewall configuration file
       
     if [ -f $CUSTOM_FIREWALL_RULES ]; then
-        echo "*filter" > $TMP_FIREWALL_CUSTOM_RULES
-        { cat "$CUSTOM_FIREWALL_RULES" | grep -v "^#" >> $TMP_FIREWALL_CUSTOM_RULES ; } || true
-        echo "-A INPUT -j REJECT --reject-with icmp-host-prohibited
--A FORWARD -j REJECT --reject-with icmp-host-prohibited
-COMMIT" >> $TMP_FIREWALL_CUSTOM_RULES
+        length=$(sed -e "s/^#.*$//g" "$CUSTOM_FIREWALL_RULES")
+        if [ ! -z "$length" ]; then
+            cat $(ls /etc/iptables/*.iptables | grep -v ip6) | grep -v COMMIT > $TMP_FIREWALL_CUSTOM_RULES
+            cat "$CUSTOM_FIREWALL_RULES" | grep -v "^#" >> $TMP_FIREWALL_CUSTOM_RULES || true
+            echo "COMMIT" >> $TMP_FIREWALL_CUSTOM_RULES
 
-        if [ -f $TMP_TEST_RULES_RESULT ]; then
-            cat "$TMP_FIREWALL_CUSTOM_RULES" | grep -v filter | grep -v COMMIT > $VALID_FIREWALL_CUSTOM_RULES
-            rm -rf $TMP_FIREWALL_CUSTOM_RULES
-            rm -rf $TMP_TEST_RULES_RESULT
+            /sbin/iptables-restore --test $TMP_FIREWALL_CUSTOM_RULES && echo "yes" > $TMP_TEST_RULES_RESULT || true
+
+            if [ -f $TMP_TEST_RULES_RESULT ]; then
+                echo "Custom firewall rules tested successfully"
+                cat "$CUSTOM_FIREWALL_RULES" | grep -v "^#" > $VALID_FIREWALL_CUSTOM_RULES || true
+                echo "$LAST_INPUT_RULES" >> "$VALID_FIREWALL_CUSTOM_RULES"
+                echo "$LAST_OUTPUT_RULE" >> "$VALID_FIREWALL_CUSTOM_RULES"
+                rm -rf $TMP_FIREWALL_CUSTOM_RULES
+                rm -rf $TMP_TEST_RULES_RESULT
+            else
+                echo "Custom firewall rules test failed. Custom rules will be ignored"
+                # There is no need to append "COMMIT", since it is included in zzzzz-footer.iptables
+                echo "$LAST_INPUT_RULES" > "$VALID_FIREWALL_CUSTOM_RULES"
+		echo "$LAST_OUTPUT_RULE" >> "$VALID_FIREWALL_CUSTOM_RULES"
+            fi
         else
-            # There is no need to append "COMMIT", since it is included in zzzzz-footer.iptables
-            echo "-A INPUT -j REJECT --reject-with icmp-host-prohibited
--A FORWARD -j REJECT --reject-with icmp-host-prohibited" > $VALID_FIREWALL_CUSTOM_RULES
+            echo "$LAST_INPUT_RULES" > "$VALID_FIREWALL_CUSTOM_RULES"
+	    echo "$LAST_OUTPUT_RULE" >> "$VALID_FIREWALL_CUSTOM_RULES"
         fi
-
     else
-        echo "-A INPUT -j REJECT --reject-with icmp-host-prohibited
--A FORWARD -j REJECT --reject-with icmp-host-prohibited" >> $VALID_FIREWALL_CUSTOM_RULES
+        echo "$LAST_INPUT_RULES" > "$VALID_FIREWALL_CUSTOM_RULES"
+	echo "$LAST_OUTPUT_RULE" >> "$VALID_FIREWALL_CUSTOM_RULES"
     fi
 
     /etc/network/if-pre-up.d/iptables > /dev/null 2>&1 || true
+}
+
+configure_default_custom_firewall () {
+    if [ -f /usr/share/alienvault-firewall/firewall_include ]; then
+       if ! [ -f /etc/ossim/firewall_include ]; then
+           cp -af /usr/share/alienvault-firewall/firewall_include /etc/ossim/
+       fi
+    fi
 }
 
 delete_deprecated_firewall_configuration(){
@@ -70,23 +88,31 @@ delete_deprecated_firewall_configuration(){
 
     # 2. Removing deprecated startup scripts from the different runlevels 
     update-rc.d -f ossim-firewall remove
+}
 
-
+flush_firewall_rules(){
+    # flushes all currently loaded firewall rules
+    /sbin/iptables -P INPUT ACCEPT
+    /sbin/iptables -P OUTPUT ACCEPT
+    /sbin/iptables -P FORWARD ACCEPT
+    /sbin/iptables -F
 }
 
 
 case "$1" in
     configure)
         # Enabling iptables filter module (first time)
-        if [ -z "$(modprobe -l iptable_filter)" ]; then
-            modprobe -q iptable_filter
+        if [ -z "$( find /lib/modules/ -type f -name "iptable_filter.ko" -exec basename {} \; )" ]; then
+            modprobe -q iptable_filter || true
             echo "Module iptable_filter was disabled, and it has been enabled"
         fi
 
-        if [ -z "$(modprobe -l ip6table_filter)" ]; then
-            modprobe -q ip6table_filter
+        if [ -z "$( find /lib/modules/ -type f -name "ip6table_filter.ko" -exec basename {} \; )" ]; then
+            modprobe -q ip6table_filter || true
             echo "Module iptable_filter was disabled, and it has been enabled"
         fi
+
+        configure_default_custom_firewall
 
         # Deleting deprecated ossim_firewall configuration
         delete_deprecated_firewall_configuration
@@ -103,7 +129,12 @@ case "$1" in
                     # Configuring firewall
                     configure_firewall
                 ;;
-
+                alienvault-config-firewall-active)
+                    configure_firewall
+                ;;
+                alienvault-config-firewall-inactive)
+                    flush_firewall_rules
+                ;;
                 *)
                     echo "postinst called with unknown trigger \`$2'">&2
                     exit 1
@@ -127,3 +158,4 @@ esac
 #DEBHELPER#
 
 exit 0
+
diff --git a/alienvault-dummies-config/debian/alienvault-mysql.postinst b/alienvault-dummies-config/debian/alienvault-mysql.postinst
--- a/alienvault-dummies-config/debian/alienvault-mysql.postinst
+++ b/alienvault-dummies-config/debian/alienvault-mysql.postinst
@@ -18,34 +18,312 @@ set -e
 # the debian-policy package
 
 OSSIM_SETUP_CONF="/etc/ossim/ossim_setup.conf"
+OSSIM_SETUP_CONF_LAST="/etc/ossim/ossim_setup.conf_last"
 DB_FIREWALL_CONF="/etc/iptables/rules006-mysql.iptables"
+MYSQL_CONF_FILE="/etc/mysql/my.cnf"
+RESTART_MYSQL=0
 
-get_ossim_param_value(){
+get_ossim_param_value() {
     mypattern="^$1="
-    value=$(egrep "$mypattern" "$OSSIM_SETUP_CONF" | cut -d'=' -f2)
+    [ "$2" = "last" ] && ossim_conf=$OSSIM_SETUP_CONF_LAST || ossim_conf=$OSSIM_SETUP_CONF
+
+    value=$(egrep "$mypattern" "$ossim_conf" | cut -d'=' -f2)
     echo $value
 }
 
+stop_mysql() {
+    set +e
+
+    retry=0
+    until ! mysqladmin ping >/dev/null 2>&1; do
+        [ 8 -le $retry ] && break
+        if [ ! -f /sbin/start-stop-daemon.REAL ]; then
+            /etc/init.d/mysql stop
+        else
+            echo "Stopping MySQL..."
+            killall -15 mysqld > /dev/null 2>&1
+        fi
+        sleep 10
+        retry=$(( $retry + 1 ))
+    done
+
+    set -e
+}
+
+start_mysql() {
+    db_ip=`get_ossim_param_value "db_ip"`
+    db_pass=`get_ossim_param_value "pass"`
+    db_user=`get_ossim_param_value "user"`
+
+    set +e
+
+    retry=0
+    until mysqladmin ping >/dev/null 2>&1; do
+        [ 8 -le $retry ] && break
+        if [ ! -f /sbin/start-stop-daemon.REAL ]; then
+            /etc/init.d/mysql start
+        else
+            echo "Starting MySQL..."
+            LD_LIBRARY_PATH="/usr/lib/alienvault/percona_toku" /usr/bin/mysqld_safe > /dev/null 2>&1 &
+        fi
+        sleep 10
+        mysqlcheck -h $db_ip -p$db_pass -u $db_user --auto-repair mysql 2>> /tmp/err
+        retry=$(( $retry + 1 ))
+    done
+
+    set -e
+}
+
+configure_mysql() {
+    # Profiles installed
+    dpkg --status alienvault-dummy-sensor > /dev/null 2>&1 && sensor=1 || sensor=0
+    dpkg --status alienvault-dummy-database > /dev/null 2>&1 && database=1 || database=0
+    dpkg --status alienvault-dummy-framework > /dev/null 2>&1 && framework=1 ||framework=0
+    dpkg --status alienvault-dummy-server > /dev/null 2>&1 && server=1 || server=0
+
+    # Ha conf
+    ha_conf=`get_ossim_param_value "ha_heartbeat_start"`
+
+    # Total memory in system (in KB)
+    MEM=$(cat /proc/meminfo | grep MemTotal | awk '{print $2}')
+
+    # Default config
+    [ -e "$MYSQL_CONF_FILE" ] && MD5_PRE=`md5sum "$MYSQL_CONF_FILE" | awk '{print $1}'` || MD5_PRE="" # If file not exists sets MD5_PRE to ""
+
+    cat > $MYSQL_CONF_FILE << EOF
+# AlienVault MySQL database server configuration file.
+
+[client]
+port=3306
+socket=/var/run/mysqld/mysqld.sock
+
+[mysqld_safe]
+socket=/var/run/mysqld/mysqld.sock
+nice=0
+
+[mysqld]
+server-id=0
+user=mysql
+pid-file=/var/run/mysqld/mysqld.pid
+socket=/var/run/mysqld/mysqld.sock
+port=3306
+basedir=/usr
+datadir=/var/lib/mysql
+tmpdir=/tmp
+language=/usr/share/mysql/english
+max_allowed_packet=512M
+event_scheduler=ON
+bind-address=0.0.0.0
+join_buffer_size=128k
+sort_buffer_size=2M
+read_rnd_buffer_size=256k
+max_heap_table_size=16M
+thread_stack=512K
+thread_cache_size=100
+transaction-isolation=READ-COMMITTED
+binlog-format=mixed
+myisam-recover=BACKUP
+max_connections=120
+key_buffer_size=64M
+tmp_table_size=16M
+thread_concurrency=10
+concurrent_insert=1
+#skip_name_resolve
+interactive_timeout=28800
+wait_timeout=28800
+slave-skip-errors=OFF
+skip-external-locking
+slave_load_tmpdir=/tmp
+tmpdir=/tmp
+
+# Query Cache Configuration
+query_cache_limit=1M
+query_cache_size=16M
+query_cache_type=1
+
+# Logging and Replication
+#general_log=On
+#slow_query_log=On
+#slow_query_log_file=/var/log/mysql/mysql-slow.log
+#long_query_time=5
+#log-queries-not-using-indexes
+#log_bin=/var/log/mysql/mysql-bin.log
+auto_increment_increment=1
+auto_increment_offset=1
+expire_logs_days=2
+max_binlog_size=100M
+#binlog_do_db=include_database_name
+#binlog_ignore_db=include_database_name
+#log-queries-not-using-indexes
+log_error=/var/log/mysql/mysql.err
+general_log_file=/var/log/mysql/mysql.log
+log_bin_trust_function_creators=OFF
+
+# InnoDB
+innodb_file_per_table=1
+innodb_fast_shutdown=0
+innodb_buffer_pool_size=134217728
+innodb_additional_mem_pool_size=8M
+#innodb_flush_method=fsync
+innodb_log_buffer_size=8M
+innodb_thread_concurrency=0
+innodb_flush_log_at_trx_commit=1
+innodb_commit_concurrency=0
+innodb_log_file_size=5M
+
+# Security Features
+# chroot=/var/lib/mysql/
+# ssl-ca=/etc/mysql/cacert.pem
+# ssl-cert=/etc/mysql/server-cert.pem
+# ssl-key=/etc/mysql/server-key.pem
+
+[mysqldump]
+quick
+quote-names
+max_allowed_packet=256M
+
+[mysql]
+#no-auto-rehash # faster start of mysql but no tab completition
+
+[isamchk]
+key_buffer_size=64M
+
+# [MYSQL_CLUSTER]
+# ndb-connectstring=127.0.0.1
+
+#!includedir /etc/mysql/conf.d/
+EOF
+
+    # High memory config
+    if [ $MEM -gt 5000000 ]; then
+        echo "Enabling high memory config..."
+
+        sed -i "s/^innodb_additional_mem_pool_size=.*/innodb_additional_mem_pool_size=20M/" $MYSQL_CONF_FILE
+        sed -i "s/^innodb_buffer_pool_size=.*/innodb_buffer_pool_size=536870912/" $MYSQL_CONF_FILE
+        sed -i "s/^innodb_flush_log_at_trx_commit=.*/innodb_flush_log_at_trx_commit=2/" $MYSQL_CONF_FILE
+        sed -i "s/^sort_buffer_size=.*/sort_buffer_size=50M/" $MYSQL_CONF_FILE
+        sed -i "s/^query_cache_limit=.*/query_cache_limit=64M/" $MYSQL_CONF_FILE
+        sed -i "s/^key_buffer_size=.*/key_buffer_size=512M/" $MYSQL_CONF_FILE
+        sed -i "s/^tmp_table_size=.*/tmp_table_size=128M/" $MYSQL_CONF_FILE
+        sed -i "s/^join_buffer_size=.*/join_buffer_size=0/" $MYSQL_CONF_FILE
+        sed -i "s/^thread_concurrency=.*/thread_concurrency=4/" $MYSQL_CONF_FILE
+        sed -i "s/^read_rnd_buffer_size=.*/read_rnd_buffer_size=2M/" $MYSQL_CONF_FILE
+        sed -i "s/^max_heap_table_size=.*/max_heap_table_size=128M/" $MYSQL_CONF_FILE
+        sed -i "s/^concurrent_insert=.*/concurrent_insert=2/" $MYSQL_CONF_FILE
+        sed -i "s/^interactive_timeout=.*/interactive_timeout=300/" $MYSQL_CONF_FILE
+        sed -i "s/^wait_timeout=.*/wait_timeout=300/" $MYSQL_CONF_FILE
+        sed -i "s/^#\?skip_name_resolve.*/skip_name_resolve/" $MYSQL_CONF_FILE
+        sed -i "s/^slave_load_tmpdir=.*/slave_load_tmpdir=\/var\/tmp/" $MYSQL_CONF_FILE
+        sed -i "s/^tmpdir=.*/tmpdir=\/var\/tmp/" $MYSQL_CONF_FILE
+        sed -i "s/^query_cache_size=.*/query_cache_size=256M/" $MYSQL_CONF_FILE
+    fi
+
+    # Is MySQL running?
+    start_mysql
+
+    mysqladmin ping > /dev/null 2>&1
+    IS_MYSQL_RUNNING=$?
+
+    MD5_POS=`md5sum "$MYSQL_CONF_FILE" | awk '{print $1}'`
+
+    if [ "$MD5_PRE" != "$MD5_POS" ] && [ $IS_MYSQL_RUNNING -eq 0 ]; then
+        # Set MySQL to restart.
+        RESTART_MYSQL=1
+    fi
+}
+
+set_grants() {
+    # If exists ossim_setup.conf_last set the last config from it
+    # If not exists set the last config equals to actual config
+    # If exists and the connection not works set the last config equals to actual config
+    start_mysql
+
+    mysqladmin ping > /dev/null 2>&1
+    IS_MYSQL_RUNNING=$?
+
+    if [ $IS_MYSQL_RUNNING -eq 0 ]; then
+        set +e
+
+        echo "Setting DB grants..."
+
+        framework_ip=$(get_ossim_param_value "framework_ip")
+        server_ip=$(get_ossim_param_value "server_ip")
+        hostname=$(get_ossim_param_value "hostname")
+        admin_ip=$(get_ossim_param_value "admin_ip")
+        pass=$(get_ossim_param_value "pass")
+
+        if [ -f $OSSIM_SETUP_CONF_LAST ]; then
+            last_framework_ip=$(get_ossim_param_value "framework_ip" "last")
+            last_server_ip=$(get_ossim_param_value "server_ip" "last")
+            last_hostname=$(get_ossim_param_value "hostname" "last")
+            last_admin_ip=$(get_ossim_param_value "admin_ip" "last")
+            last_pass=$(get_ossim_param_value "pass" "last")
+
+            TEST_QUERY=`sshpass -p $last_pass mysql -uroot -p -e "SELECT 1" 2>&1`
+            ERROR=`echo $TEST_QUERY | grep -ni "ERROR"`
+        fi
+
+        if [ ! -z "$ERROR" ] || [ ! -z "${ERROR-NO_INSTANCE}" ]; then
+            last_framework_ip=$framework_ip
+            last_server_ip=$server_ip
+            last_hostname=$hostname
+            last_admin_ip=$admin_ip
+            last_pass=$pass
+        fi
+
+        mysql -uroot -p$last_pass -e \
+        "UPDATE IGNORE mysql.user SET host=LOWER(host);
+        GRANT USAGE ON *.* TO root@'$last_framework_ip';
+        DROP USER root@'$last_framework_ip';
+        GRANT USAGE ON *.* TO ocs@'$last_framework_ip';
+        DROP USER ocs@'$last_framework_ip';
+        GRANT USAGE ON *.* TO root@'$last_admin_ip';
+        DROP USER root@'$last_admin_ip';
+        GRANT USAGE ON *.* TO root@'$last_server_ip';
+        DROP USER root@'$last_server_ip';
+        GRANT USAGE ON *.* TO root@'$last_hostname';
+        DROP USER root@'$last_hostname';
+        GRANT ALL ON *.* TO root@'$framework_ip' IDENTIFIED BY '$pass';
+        GRANT ALL ON *.* TO ocs@'$framework_ip' IDENTIFIED BY '$pass';
+        GRANT ALL ON *.* TO root@'$admin_ip' IDENTIFIED BY '$pass';
+        GRANT ALL ON *.* TO root@'$server_ip' IDENTIFIED BY '$pass';
+        GRANT ALL ON *.* TO root@'$hostname' IDENTIFIED BY '$pass';
+        GRANT ALL ON *.* TO root@'127.0.0.1' IDENTIFIED BY '$pass';
+        GRANT ALL ON *.* TO root@'localhost' IDENTIFIED BY '$pass';
+        GRANT ALL ON *.* TO root@'::1' IDENTIFIED BY '$pass';
+        FLUSH PRIVILEGES;"
+
+        set -e
+    fi
+}
+
 configure_firewall(){
-    
+
+    admin_ip=$(get_ossim_param_value "admin_ip")
     server_ip=$(get_ossim_param_value "server_ip")
     framework_ip=$(get_ossim_param_value "framework_ip")
 
     if [ -f $DB_FIREWALL_CONF ]; then
-        if [ ${#server_ip} != 0 ]; then
+        if [ ${#server_ip} != 0 ] && [ ${#admin_ip} != 0 ] && [ ${server_ip} != ${admin_ip} ]; then
 	    sed -i "s/SERVERIP/$server_ip/g" $DB_FIREWALL_CONF
         else
-            echo "server_ip parameter in ossim_setup.conf is empty. iptables rules using server_ip value will be skipped"
+            echo "Skipping iptables rules for allowing connections to local MySQL DB from server_ip ${server_ip}"
 	    for numline in $(grep -rne SERVERIP $DB_FIREWALL_CONF | cut -d':' -f1); do
+                sed -i "$numline s/^/#/" $DB_FIREWALL_CONF
+            done
+            for numline in $(grep -rne "${admin_ip}" $DB_FIREWALL_CONF | grep -v ":#" | cut -d':' -f1); do
                 sed -i "$numline s/^/#/" $DB_FIREWALL_CONF
             done
         fi
 
-        if [ ${#framework_ip} != 0 ]; then
+        if [ ${#framework_ip} != 0 ] && [ ${#admin_ip} != 0 ] && [ ${framework_ip} != ${admin_ip} ]; then
             sed -i "s/FRAMEWORKIP/$framework_ip/g" $DB_FIREWALL_CONF
         else
-            echo "framework_ip parameter in ossim_setup.conf is empty. iptables rules using framework_ip value will be skipped"
+            echo "Skipping iptables rules for allowing connections to local MySQL DB from framework_ip ${framework_ip}"
             for numline in $(grep -rne FRAMEWORKIP $DB_FIREWALL_CONF | cut -d':' -f1); do
+                sed -i "$numline s/^/#/" $DB_FIREWALL_CONF
+            done
+            for numline in $(grep -rne "${admin_ip}" $DB_FIREWALL_CONF | grep -v ":#" | cut -d':' -f1); do
                 sed -i "$numline s/^/#/" $DB_FIREWALL_CONF
             done
         fi
@@ -55,7 +333,6 @@ configure_firewall(){
     fi
 
     dpkg-trigger --no-await alienvault-restart-firewall
-    
 }
 
 update_serverip_iptables(){
@@ -67,7 +344,7 @@ update_serverip_iptables(){
         sed -i "s/^#//g" $DB_FIREWALL_CONF
         ft_counter=$(grep -c SERVERIP $DB_FIREWALL_CONF | cat)
         if [ "$ft_counter" != "0" ]; then
-            sed -i "s/SERVERIP/$framework_ip/g" $DB_FIREWALL_CONF
+            sed -i "s/SERVERIP/$server_ip/g" $DB_FIREWALL_CONF
         else
             old_server_ip=$(sed -n 1p $DB_FIREWALL_CONF | cut -d' ' -f14)
             sed -i "s/$old_server_ip/$server_ip/g" $DB_FIREWALL_CONF
@@ -95,24 +372,43 @@ update_frameworkip_iptables(){
     fi
 
 }
-
-
 case "$1" in
     configure)
         configure_firewall
+        set_grants
+        configure_mysql
     ;;
 
     triggered)
+        SET_DEFAULT_CONFIG=0
+        RESTART_FIREWALL=0
+        CHANGED_IF_GRANTS=0
+
         for trigger in $2
         do
             case "$trigger" in
+                alienvault-mysql-set-default-config)
+                    CHANGED_IF_GRANTS=1
+                    SET_DEFAULT_CONFIG=1
+                    ;;
                 alienvault-config-server-server-ip)
                     update_serverip_iptables
-                    dpkg-trigger --no-await alienvault-restart-firewall
+                    RESTART_FIREWALL=1
+                    CHANGED_IF_GRANTS=1
                     ;;
                 alienvault-config-framework-framework-ip)
                     update_frameworkip_iptables
-                    dpkg-trigger --no-await alienvault-restart-firewall
+                    RESTART_FIREWALL=1
+                    CHANGED_IF_GRANTS=1
+                    ;;
+                alienvault-config-ha-ha-heartbeat-start|alienvault-config-ha-ha-role)
+                    SET_DEFAULT_CONFIG=1
+                    ;;
+                alienvault-mysql-set-grants|alienvault-config-database-pass|alienvault-config-system-hostname|alienvault-config-system-admin-ip)
+                    CHANGED_IF_GRANTS=1
+                    ;;
+                alienvault-restart-mysql)
+                    RESTART_MYSQL=1
                     ;;
                 *)
                     echo "postinst called with unknown trigger \`$2'">&2
@@ -120,6 +416,18 @@ case "$1" in
                     ;;
             esac
         done
+
+        if [ $SET_DEFAULT_CONFIG -ne 0 ]; then
+            configure_mysql
+        fi
+
+        if [ $RESTART_FIREWALL -ne 0 ]; then
+            dpkg-trigger --no-await alienvault-restart-firewall
+        fi
+
+        if [ $CHANGED_IF_GRANTS -ne 0 ]; then
+            set_grants
+        fi
     ;;
 
     abort-upgrade|abort-remove|abort-deconfigure)
@@ -130,6 +438,11 @@ case "$1" in
         exit 1
     ;;
 esac
+
+if [ $RESTART_MYSQL -ne 0 ]; then
+    stop_mysql
+    start_mysql
+fi
 
 # dh_installdeb will replace this with shell code automatically
 # generated by other debhelper scripts.
diff --git a/alienvault-dummies-config/debian/alienvault-vpn.postinst b/alienvault-dummies-config/debian/alienvault-vpn.postinst
--- a/alienvault-dummies-config/debian/alienvault-vpn.postinst
+++ b/alienvault-dummies-config/debian/alienvault-vpn.postinst
@@ -1,10 +1,9 @@
-#!/bin/sh
+#
 # postinst script for alienvault-vpn
 #
 # see: dh_installdeb(1)
 
 set -e
-
 # summary of how this script can be called:
 #        * <postinst> `configure' <most-recently-configured-version>
 #        * <old-postinst> `abort-upgrade' <new version>
@@ -18,35 +17,210 @@ set -e
 # the debian-policy package
 
 OSSIM_SETUP_CONF="/etc/ossim/ossim_setup.conf"
+VPN_CORE_CONF_FILE="/etc/alienvault/network/vpn.conf"
 VPN_IPTABLES_CONF="/etc/iptables/rules004-vpn.iptables"
+
+# Check if we have to use 1024 or 2048 key size
+VPN_DH_PEM=""
+VPN_DH_1024_PEM="/etc/openvpn/AVinfraestructure/keys/dh1024.pem"
+VPN_DH_2048_PEM="/etc/openvpn/AVinfraestructure/keys/dh2048.pem"
+[ -f $VPN_DH_1024_PEM ] && VPN_DH_PEM=$VPN_DH_1024_PEM || VPN_DH_PEM=$VPN_DH_2048_PEM
+
+VPN_CONF_TEMPLATE=$(cat <<EOF
+# Configuration file provided by the alienvault-vpn package.
+port VPN_PORT
+proto tcp
+dev tun
+server VPN_NET.0 VPN_NETMASK
+ca /etc/openvpn/AVinfraestructure/keys/ca.crt
+cert /etc/openvpn/AVinfraestructure/keys/alienvcd.crt
+key /etc/openvpn/AVinfraestructure/keys/alienvcd.key
+dh /etc/openvpn/AVinfraestructure/keys/dh2048.pem
+user nobody
+group nogroup
+verb 3
+mute 20
+keepalive 10 120
+client-config-dir /etc/openvpn/ccd
+comp-lzo
+persist-key
+persist-tun
+ccd-exclusive
+client-to-client
+EOF
+                 )
+
+EASY_RSA_PATH="/usr/share/easy-rsa"
+export OPENSSL="openssl"
+EASY_RSA_VARS_TEMPLATE=$(cat <<EOF
+# Configuration file provided by the alienvault-vpn package.
+export EASY_RSA="$EASY_RSA_PATH"
+export OPENSSL="openssl"
+export PKCS11TOOL="pkcs11-tool"
+export GREP="grep"
+export KEY_CONFIG=$($EASY_RSA_PATH/whichopensslcnf $EASY_RSA_PATH)
+export KEY_DIR="$EASY_RSA_PATH/keys"
+export PKCS11_MODULE_PATH="dummy"
+export PKCS11_PIN="dummy"
+export KEY_SIZE=2048
+export CA_EXPIRE=3650
+export KEY_EXPIRE=3650
+export KEY_COUNTRY="ES"
+export KEY_PROVINCE="ES"
+export KEY_CITY="Madrid"
+export KEY_ORG="Alienvault"
+export KEY_EMAIL="root@alienvault.com"
+EOF
+             )
+
 
 get_ossim_param_value(){
     mypattern="^$1="
     value=$(egrep "$mypattern" "$OSSIM_SETUP_CONF" | cut -d'=' -f2)
     echo $value
-} 
+}
 
+# Read param from vpn configuration file
+read_from_config_file(){
+    VPN_CONF_FILE="/etc/alienvault/network/vpn.conf"
+
+    VPN_INTERFACE=$1
+    VPN_VALUE=$2 
+
+    VPN_ENTRY="/files$VPN_CORE_CONF_FILE/$VPN_INTERFACE"
+
+    value=$(augtool --noautoload <<EOF
+set /augeas/load/Puppet/lens "Puppet.lns"
+set /augeas/load/Puppet/incl "$VPN_CORE_CONF_FILE"
+load
+print "$VPN_ENTRY/$VPN_VALUE"
+quit 
+EOF
+)
+    value=$(echo $value | cut -d'=' -f2 | tr -d ' ')
+    echo $value | tr -d '"' 
+}
+
+# Set params in vpn configuration file
+write_to_config_file() {
+
+    VPN_PARAMS="$1"
+
+    VPN_INTERFACE=$(echo "$VPN_PARAMS" | cut -d' ' -f1)
+    VPN_ROLE=$(echo "$VPN_PARAMS" | cut -d' ' -f2)
+    VPN_CONFIG_FILE=$(echo "$VPN_PARAMS" | cut -d' ' -f3)    
+    VPN_NETWORK=$(echo "$VPN_PARAMS" | cut -d' ' -f4)
+    VPN_NETMASK=$(echo "$VPN_PARAMS" | cut -d' ' -f5)
+    VPN_PORT=$(echo "$VPN_PARAMS" | cut -d' ' -f6)
+    VPN_CA=$(echo "$VPN_PARAMS" | cut -d' ' -f7)
+    VPN_CERT=$(echo "$VPN_PARAMS" | cut -d' ' -f8)
+    VPN_KEY=$(echo "$VPN_PARAMS" | cut -d' ' -f9)
+    VPN_DH=$(echo "$VPN_PARAMS" | cut -d' ' -f10)
+    VPN_ENABLED=$(echo "$VPN_PARAMS" | cut -d' ' -f11)    
+
+    VPN_ENTRY="/files$VPN_CORE_CONF_FILE/$VPN_INTERFACE"
+
+    augtool --noautoload  <<EOF
+set /augeas/load/Puppet/lens "Puppet.lns"
+set /augeas/load/Puppet/incl "$VPN_CORE_CONF_FILE"
+load
+set "$VPN_ENTRY/role" $VPN_ROLE
+set "$VPN_ENTRY/config_file" $VPN_CONFIG_FILE
+set "$VPN_ENTRY/network" $VPN_NETWORK
+set "$VPN_ENTRY/netmask" $VPN_NETMASK
+set "$VPN_ENTRY/port" $VPN_PORT
+set "$VPN_ENTRY/ca" $VPN_CA
+set "$VPN_ENTRY/cert" $VPN_CERT
+set "$VPN_ENTRY/key" $VPN_KEY
+set "$VPN_ENTRY/dh" $VPN_DH
+set "$VPN_ENTRY/enabled" $VPN_ENABLED
+save
+quit
+EOF
+}
+
+# Migrate from the old configuration format, found in /etc/ossim/ossim_setup.conf, to a new one.
+# This method should be straightforward, because it only allowed one active VPN configuration, with tun0 as the interface.
+migrate_config_params() {
+
+    from_trigger="$1"
+
+    ADMIN_IP=$(get_ossim_param_value "admin_ip")
+    VPN_CLIENT_CONFIG_FILE="/etc/openvpn/$ADMIN_IP.conf"
+    VPN_SERVER_CONFIG_FILE="/etc/openvpn/AVinfraestructure.conf"
+
+    VPN_ROLE="server"
+    VPN_CONFIG_FILE="$VPN_SERVER_CONFIG_FILE"
+    if [ -f "$VPN_CLIENT_CONFIG_FILE" ]; then
+        VPN_ROLE="client"
+        VPN_CONFIG_FILE="$VPN_CLIENT_CONFIG_FILE"
+    fi
+
+    VPN_NETWORK=$(get_ossim_param_value "vpn_net")
+    VPN_NETMASK=$(get_ossim_param_value "vpn_netmask")
+    VPN_PORT=$(get_ossim_param_value "vpn_port")
+    VPN_CA="/etc/openvpn/AVinfraestructure/keys/ca.crt"
+    VPN_CERT="/etc/openvpn/AVinfraestructure/keys/alienvcd.crt"
+    VPN_KEY="/etc/openvpn/AVinfraestructure/keys/alienvcd.key"
+
+    VPN_DH="$VPN_DH_PEM"
+    if [ "$from_trigger" = "1" ]; then
+        if [ -f "/etc/openvpn/1024.keysize" ]; then
+            VPN_DH="$VPN_DH_1024_PEM"
+            rm -f "/etc/openvpn/1024.keysize"
+        else
+            VPN_DH="$VPN_DH_2048_PEM"
+            rm -f "/etc/openvpn/2048.keysize"
+        fi
+    else
+        if [ -f "$VPN_CORE_CONF_FILE" ]; then
+            VPN_DH=$(read_from_config_file "$VPN_ACTIVE_INTERFACE" "dh")
+        fi
+    fi
+
+
+    if [ "$from_trigger" = "0" ]; then
+        openvpn_found=$(pgrep -f "/usr/sbin/openvpn" || echo "Not enabled")
+        if [ "$openvpn_found" = "Not enabled" ]; then
+            echo "openvpn is not running. Setting it as disable initially"
+            VPN_ENABLED="no"
+        else
+            echo "openvpn is running. Setting it as enable initially"
+            VPN_ENABLED="yes"
+        fi
+    else
+        VPN_ENABLED="yes"
+    fi
+
+    VPN_PARAMS="$VPN_ACTIVE_INTERFACE $VPN_ROLE $VPN_CONFIG_FILE"
+    VPN_PARAMS="$VPN_PARAMS $VPN_NETWORK $VPN_NETMASK $VPN_PORT $VPN_CA $VPN_CERT"
+    VPN_PARAMS="$VPN_PARAMS $VPN_KEY $VPN_DH $VPN_ENABLED"
+
+    write_to_config_file "$VPN_PARAMS"
+}
+
+
+# Create firewall rules for the VPN configuration
 configure_firewall() {
-    vpn_enabled=$(get_ossim_param_value "vpn_infraestructure")
-    vpn_port=$(get_ossim_param_value "vpn_port")
+    
+    VPN_ENABLED=$(read_from_config_file "$VPN_ACTIVE_INTERFACE" "enabled")
+    VPN_PORT=$(read_from_config_file "$VPN_ACTIVE_INTERFACE" "port")
     RET=1
-    MD5_PREV=`md5sum "$VPN_IPTABLES_CONF" |awk '{print $1}'`
+    MD5_PREV=$(md5sum "$VPN_IPTABLES_CONF" |awk '{print $1}')
 
     # vpn_infraestructure enabled
-    if [ "$vpn_enabled" = "yes" ]; then
+    if [ "$VPN_ENABLED" = "yes" ]; then
         echo "# VPN Rules
--A INPUT -p tcp -m state --state NEW -m tcp --dport $vpn_port -j ACCEPT
+-A INPUT -p tcp -m state --state NEW -m tcp --dport $VPN_PORT -j ACCEPT
 -A INPUT -i tun+ -j ACCEPT
--A FORWARD -i tun+ -j ACCEPT
--A OUTPUT -o tun+ -j ACCEPT
--A FORWARD -o tun+ -j ACCEPT" > $VPN_IPTABLES_CONF
+-A OUTPUT -o tun+ -j ACCEPT " > $VPN_IPTABLES_CONF
     else
         echo "VPN configuration is disabled or unknown. There wont be any rules configured for VPN"
         echo "# VPN Rules" > $VPN_IPTABLES_CONF
     fi
 
     # Check if the vpn-rules.iptables file has changed
-    MD5_POST=`md5sum "$VPN_IPTABLES_CONF" |awk '{print $1}'`
+    MD5_POST=$(md5sum "$VPN_IPTABLES_CONF" |awk '{print $1}')
 
     if [ "$MD5_PREV" != "$MD5_POST" ]; then
         RET=$((RET&0))
@@ -57,21 +231,192 @@ configure_firewall() {
         dpkg-trigger --no-await alienvault-restart-firewall
         echo "Firewall rules updated with vpn configuration"
     fi
-
 }
 
 
+# Generate server certs
+configure_server_certs() {
+    SERVER_PROFILE=$(grep -m1 "profile=" "$OSSIM_SETUP_CONF" | cut -d'=' -f2 |grep -o 'Server')
+    ADMIN_IP=$(get_ossim_param_value "admin_ip")
+    VPN_NET=$(read_from_config_file "$VPN_ACTIVE_INTERFACE" "network")
+    VPN_NETMASK=$(read_from_config_file "$VPN_ACTIVE_INTERFACE" "netmask")
+    VPN_PORT=$(read_from_config_file "$VPN_ACTIVE_INTERFACE" "port")
+
+    VPN_CONF_FILE="/etc/openvpn/AVinfraestructure.conf"
+    VPN_DIR="/etc/openvpn/AVinfraestructure"
+    VPN_KEY_DIR="$VPN_DIR/keys"
+    VPN_CLIENT_DIR="/etc/openvpn/$ADMIN_IP"
+
+    EASY_RSA_DIR="$EASY_RSA_PATH"
+    EASY_RSA_VARS_FILE="$EASY_RSA_DIR/vars"
+    
+    BLACKLIST_4096_DIR="/usr/share/openssl-blacklist"
+    BLACKLIST_4096_FILE="$BLACKLIST_4096_DIR/blacklist.RSA-4096"
+
+    # This only applies on 'Server' profiles.
+    if [ -z "$SERVER_PROFILE" ]; then
+        return
+    fi
+
+    # This only applies if it is not already configured as a VPN client.
+    if [ -d "$VPN_CLIENT_DIR" ]; then
+        return
+    fi
+
+    # Set up the VPN server configuration directory, if needed.
+    if [ ! -d "$VPN_DIR" ] && [ ! -d "$VPN_KEY_DIR" ]; then
+        mkdir -p -m 0750 "$VPN_DIR"
+        mkdir -p -m 0750 "$VPN_KEY_DIR"
+
+        # Set openvpn server configuration files.
+        echo "$VPN_CONF_TEMPLATE" | \
+            sed -e "s:^port .*$:port ${VPN_PORT}:g" \
+                -e "s:^server .*$:server ${VPN_NET}\.0 ${VPN_NETMASK}:g" \
+                > "$VPN_CONF_FILE"
+
+        # Update dh in vpn.conf
+        if [ -f "$VPN_CORE_CONF_FILE" ]; then
+            sed -i "s:^dh=.*$:dh=$VPN_DH_2048_PEM:g" "$VPN_CORE_CONF_FILE"
+        fi
+
+        # Create cryptographic files.
+        echo "$EASY_RSA_VARS_TEMPLATE" > "$EASY_RSA_VARS_FILE"
+
+        cd "$EASY_RSA_DIR"
+        . "$EASY_RSA_VARS_FILE"
+
+        ./clean-all > /dev/null 2>&1
+        ./build-dh > /dev/null 2>&1
+        ./pkitool --initca > /dev/null 2>&1
+        ./pkitool --server alienvcd > /dev/null 2>&1
+        cp -rf keys/* "$VPN_KEY_DIR"
+    fi
+
+    # OpenVPN requires client-config-dir to exist in the server to start VPN
+    VPN_CCD_DIR="/etc/openvpn/ccd"
+    [ -d "$VPN_CCD_DIR" ] || mkdir -p "$VPN_CCD_DIR"
+
+    # Avoid a common openvpn complaint: "could not open database for 4096 bits"
+    # (https://help.ubuntu.com/community/OpenVPN)
+    # This workaround requires openssl-blacklist directory to exist, but jessie does not
+    # have this dependency, so we will create that dir manually
+    [ -d "$BLACKLIST_4096_DIR" ] || mkdir -p "$BLACKLIST_4096_DIR"
+    [ -f "$BLACKLIST_4096_FILE" ] || touch "$BLACKLIST_4096_FILE"
+}
+
+configure_vpn() {
+    SERVER_PROFILE=$(grep -m1 "profile=" "$OSSIM_SETUP_CONF" | cut -d'=' -f2 |grep -o 'Server' || echo "")
+
+    VPN_DIR="/etc/openvpn/AVinfraestructure"
+    VPN_NODES_DIR="/etc/openvpn/nodes"
+    VPN_CCD_DIR="/etc/openvpn/ccd"
+
+    SYSTEM_ID=$(alienvault-api system_id)
+
+    VPN_ENABLE_DISABLE=$1
+    VPN_SET_PARAMS=$2
+
+    if [ -n "$SERVER_PROFILE" ]; then
+        SERVER_ID=$(echo "SELECT HEX(server_id) FROM alienvault.system WHERE id = UNHEX(REPLACE('$SYSTEM_ID', '-', ''));" | ossim-db | tail -n1)
+        SERVER_IP=$(echo "SELECT INET6_NTOA(admin_ip) FROM alienvault.system WHERE id = UNHEX(REPLACE('$SYSTEM_ID', '-', ''));" | ossim-db | tail -n1)
+    fi
+
+    ## Do actual stuff.
+
+    # Change VPN configuration parameters.
+    VPN_ROLE=$(read_from_config_file "$VPN_ACTIVE_INTERFACE" "role")
+    if [ $VPN_SET_PARAMS -eq 1 ] && [ "$VPN_ROLE" = "server" ]; then
+        # Clean configuration files.
+        # If the VPN server configuration changes, unfortunately these have to change too.
+        rm -rf "$VPN_DIR" "$VPN_NODES_DIR" "$VPN_CCD_DIR"
+        configure_server_certs
+        VPN_ENABLE_DISABLE=1
+        	
+    fi
+
+    # Enable or disable the VPN service.
+    if [ $VPN_ENABLE_DISABLE -eq 1 ]; then
+        VPN_ENABLED=$(read_from_config_file "$VPN_ACTIVE_INTERFACE" "enabled") 
+        if [ "$VPN_ENABLED" = "yes" ]; then
+            # Insert and restart service.
+            insserv -d openvpn
+            /etc/init.d/openvpn restart
+  
+            # Update the database.
+            if [ -n "$SERVER_PROFILE" ]; then
+
+                # Get the current VPN IP address.
+                sleep 5
+                NEW_VPN_IP=$(ifconfig tun0 | grep -Po 'inet\saddr\:\K\S+')
+                OLD_VPN_IP=$(echo "select INET6_NTOA(ip) from alienvault.server where id=UNHEX(REPLACE('$SYSTEM_ID', '-', ''));" | ossim-db | tail -n 1) 
+                
+                if [ "$NEW_VPN_IP" != "$OLD_VPN_IP" ]; then
+                   
+                    UPDATE_SYSTEM_QUERY="UPDATE alienvault.system SET vpn_ip = INET6_ATON('$NEW_VPN_IP') WHERE id = UNHEX(REPLACE('$SYSTEM_ID', '-', ''));"
+                    echo "$UPDATE_SYSTEM_QUERY" | ossim-db || true
+                
+                    UPDATE_SERVER_QUERY="UPDATE alienvault.server SET ip = INET6_ATON('$NEW_VPN_IP') WHERE id = 0x$SERVER_ID;"
+                    echo "$UPDATE_SERVER_QUERY" | ossim-db || true
+
+                    /etc/init.d/alienvault-forward restart 
+                fi
+            fi
+
+        elif [ "$VPN_ENABLED" = "no" ]; then
+            # Delete and stop  the service.
+            insserv -r openvpn
+            /etc/init.d/openvpn stop
+
+            # Update the database.
+            if [ -n "$SERVER_PROFILE" ]; then
+                echo "UPDATE alienvault.system SET vpn_ip = NULL WHERE id = UNHEX(REPLACE('$SYSTEM_ID', '-', ''));" | ossim-db
+                echo "UPDATE alienvault.server SET ip = INET6_ATON('$SERVER_IP') WHERE id = 0x$SERVER_ID;" | ossim-db
+                /etc/init.d/alienvault-forward restart 
+            fi
+        else
+            echo "VPN infrastructure field in file ossim_setup.conf is corrupted"
+            exit -1
+        fi
+    fi
+}
+
+
+# If VPN interface is not present, there is nothing to configure
+VPN_ACTIVE_INTERFACE=$(ifconfig | grep -o tun0 || echo "")
+if [ -z "$VPN_ACTIVE_INTERFACE" ]; then
+    echo "VPN interface is not configured. Using tun0 (default)"
+    VPN_ACTIVE_INTERFACE="tun0"
+fi
+
 case "$1" in
     configure)
+        VPN_TRIGGERED=0
+        migrate_config_params "$VPN_TRIGGERED"
         configure_firewall
     ;;
 
     triggered)
+        VPN_ENABLE_DISABLE=0
+        VPN_SET_PARAMS=0
+
+        if [ ! -f "$VPN_CORE_CONF_FILE" ]; then
+            echo "VPN configuration file not found. Nothing to configure"
+            exit 0
+        fi
+
         for trigger in $2
         do
             case "$trigger" in
-                alienvault-config-vpn-vpn-infraestructure)
-                    configure_firewall
+                alienvault-network-vpn-enabled)
+                    VPN_ENABLE_DISABLE=1
+                    ;;
+                alienvault-network-vpn-net-config|alienvault-network-vpn-crypto-config)
+                    VPN_SET_PARAMS=1
+                    ;;
+                alienvault-network-vpn-net-client)
+                    VPN_TRIGGERED=1
+                    migrate_config_params "$VPN_TRIGGERED"
+                    VPN_ENABLE_DISABLE=1
                     ;;
                 *)
                     echo "postinst called with unknown trigger \`$2'">&2
@@ -79,6 +424,8 @@ case "$1" in
                 ;;
             esac
         done
+        configure_firewall
+        configure_vpn $VPN_ENABLE_DISABLE $VPN_SET_PARAMS
     ;;
 
     abort-upgrade|abort-remove|abort-deconfigure)
diff --git a/os-sim/agent/debian/ossim-agent.init b/os-sim/agent/debian/ossim-agent.init
--- a/os-sim/agent/debian/ossim-agent.init
+++ b/os-sim/agent/debian/ossim-agent.init
@@ -3,15 +3,13 @@
 # Provides:          ossim-agent
 # Required-Start:    $syslog $network $remote_fs $time $local_fs
 # Required-Stop:     $syslog $network $remote_fs $time $local_fs
-# Should-Start:      alienvault-idm ossim-server
-# Should-Stop:       alienvault-idm ossim-server
+# Should-Start:      ossim-server redis-server
+# Should-Stop:       ossim-server redis-server
 # Default-Start:     2 3 4 5
 # Default-Stop:      0 1 6
 # Short-Description: Open Source Security Information Management Agent
 # Description:       Gathers and sends data to the correlation engine for further process.
 ### END INIT INFO
-
-set -e
 
 . /lib/lsb/init-functions
 
@@ -19,7 +17,8 @@ PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
 DESC="OSSIM Agent"
 NAME=ossim-agent
 DAEMON=/usr/bin/$NAME
-PIDFILE=/var/run/$NAME.pid
+RUNDIR=/var/run
+PIDFILE=$RUNDIR/$NAME.pid
 SCRIPTNAME=/etc/init.d/$NAME
 RUNNING_INSTANCE_EXITS_E=2
 # Gracefully exit if the package has been removed.
@@ -37,10 +36,37 @@ d_start() {
        exit $RUNNING_INSTANCE_EXITS_E
    fi
 
+   # Check if /var/run is a symbolic link to determine the Debian configuration
+   if [ -h $RUNDIR ]; then
+      # Wheezy
+      mount | grep "/run type" > /dev/null
+      if [ "$?" = "1" ]; then
+         log_daemon_msg "ERROR: /run is not mounted yet. The system is not stable. Skipping"
+         exit 1
+      fi
+   else
+      # Squeeze
+      log_daemon_msg "ossim-agent running on squeeze"
+   fi 
+
    # If pidfile exists, we remove it before start.
    if [ -f $PIDFILE ]
    then
        rm -rf $PIDFILE
+   fi
+
+   # Check if there are files in the future under suricata logs, and remove them
+   if [ -d "/var/log/suricata" ]; then
+       if ls -rt /var/log/suricata/unified2.alert.* &> /dev/null; then
+           log_files=$(ls -rt /var/log/suricata/unified2.alert.*)
+           now=$(date +%s)
+           for file in $log_files; do
+               filetime=$(echo $file | cut -d'.' -f3)
+               if [ "$filetime" -gt "$now" ]; then
+                   rm -f $file
+               fi
+           done
+       fi
    fi
 
    start-stop-daemon -b --quiet --start --pidfile $PIDFILE \
@@ -83,6 +109,13 @@ d_stop() {
             log_daemon_msg "PIDFILE exists but no process running... remove pidfile"
             rm -rf $PIDFILE
         fi
+    fi
+
+    # if there are nmap processes running - kill them.
+    running_nmap=`pgrep nmap | wc -l`
+    if [ $running_nmap -gt 0 ]
+    then
+       kill -9 `pgrep nmap` > /dev/null
     fi
 }
 
diff --git a/os-sim/debian/ossim-framework-daemon.ossim-framework.init b/os-sim/debian/ossim-framework-daemon.ossim-framework.init
--- a/os-sim/debian/ossim-framework-daemon.ossim-framework.init
+++ b/os-sim/debian/ossim-framework-daemon.ossim-framework.init
@@ -20,7 +20,8 @@ PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
 DESC="OSSIM Framework"
 NAME=ossim-framework
 DAEMON=/usr/bin/$NAME
-PIDFILE=/var/run/$NAME.pid
+RUNDIR=/var/run
+PIDFILE=$RUNDIR/$NAME.pid
 SCRIPTNAME=/etc/init.d/$NAME
 RUNNING_INSTANCE_EXITS_E=2
 
@@ -65,6 +66,20 @@ d_start() {
         exit $RUNNING_INSTANCE_EXITS_E
    fi     
    
+   # Check if /var/run is a symbolic link to determine the Debian configuration
+   if [ -h $RUNDIR ]; then
+      # Wheezy
+      mount | grep "/run type" > /dev/null
+      if [ "$?" = "1" ]; then
+         log_daemon_msg "ERROR: /run is not mounted yet. The system is not stable. Skipping"
+         exit 1
+      fi
+   else
+      # Squeeze
+      log_daemon_msg "ossim-server running on squeeze"
+   fi
+
+
    # If pidfile exists, we remove it before start.    
    if [ -f $PIDFILE ]
       then
