Updated

diff --git a/alienvault-api/alienvault-api/scripts/celerybeat b/alienvault-api/alienvault-api/scripts/celerybeat
--- a/alienvault-api/alienvault-api/scripts/celerybeat
+++ b/alienvault-api/alienvault-api/scripts/celerybeat
@@ -1,4 +1,4 @@
-#!/bin/bash
+#!/bin/sh -e
 # =========================================================
 #  celerybeat - Starts the Celery periodic task scheduler.
 # =========================================================
@@ -20,6 +20,92 @@
 # Cannot use set -e/bash -e since the kill -0 command will abort
 # abnormally in the absence of a valid process ID.
 #set -e
+VERSION=10.1
+echo "celery init v${VERSION}."
+
+if [ $(id -u) -ne 0 ]; then
+    echo "Error: This program can only be used by the root user."
+    echo "       Unpriviliged users must use 'celery beat --detach'"
+    exit 1
+fi
+
+origin_is_runlevel_dir () {
+    set +e
+    dirname $0 | grep -q "/etc/rc.\.d"
+    echo $?
+}
+
+# Can be a runlevel symlink (e.g. S02celeryd)
+if [ $(origin_is_runlevel_dir) -eq 0 ]; then
+    SCRIPT_FILE=$(readlink "$0")
+else
+    SCRIPT_FILE="$0"
+fi
+SCRIPT_NAME="$(basename "$SCRIPT_FILE")"
+
+# /etc/init.d/celerybeat: start and stop the celery periodic task scheduler daemon.
+
+# Make sure executable configuration script is owned by root
+_config_sanity() {
+    local path="$1"
+    local owner=$(ls -ld "$path" | awk '{print $3}')
+    local iwgrp=$(ls -ld "$path" | cut -b 6)
+    local iwoth=$(ls -ld "$path" | cut -b 9)
+
+    if [ "$(id -u $owner)" != "0" ]; then
+        echo "Error: Config script '$path' must be owned by root!"
+        echo
+        echo "Resolution:"
+        echo "Review the file carefully and make sure it has not been "
+        echo "modified with mailicious intent.  When sure the "
+        echo "script is safe to execute with superuser privileges "
+        echo "you can change ownership of the script:"
+        echo "    $ sudo chown root '$path'"
+        exit 1
+    fi
+
+    if [ "$iwoth" != "-" ]; then  # S_IWOTH
+        echo "Error: Config script '$path' cannot be writable by others!"
+        echo
+        echo "Resolution:"
+        echo "Review the file carefully and make sure it has not been "
+        echo "modified with malicious intent.  When sure the "
+        echo "script is safe to execute with superuser privileges "
+        echo "you can change the scripts permissions:"
+        echo "    $ sudo chmod 640 '$path'"
+        exit 1
+    fi
+    if [ "$iwgrp" != "-" ]; then  # S_IWGRP
+        echo "Error: Config script '$path' cannot be writable by group!"
+        echo
+        echo "Resolution:"
+        echo "Review the file carefully and make sure it has not been "
+        echo "modified with malicious intent.  When sure the "
+        echo "script is safe to execute with superuser privileges "
+        echo "you can change the scripts permissions:"
+        echo "    $ sudo chmod 640 '$path'"
+        exit 1
+    fi
+}
+
+scripts=""
+
+if test -f /etc/default/celeryd; then
+    scripts="/etc/default/celeryd"
+    _config_sanity /etc/default/celeryd
+    . /etc/default/celeryd
+fi
+
+EXTRA_CONFIG="/etc/default/${SCRIPT_NAME}"
+if test -f "$EXTRA_CONFIG"; then
+    scripts="$scripts, $EXTRA_CONFIG"
+    _config_sanity "$EXTRA_CONFIG"
+    . "$EXTRA_CONFIG"
+fi
+
+echo "Using configuration: $scripts"
+
+
 DEFAULT_RUN_DIR=/var/run
 DEFAULT_PID_DIR=$DEFAULT_RUN_DIR/alienvault
 DEFAULT_PID_FILE=$DEFAULT_PID_DIR/beat.pid
@@ -31,18 +117,22 @@ DEFAULT_WORKDIR=/usr/share/alienvault/
 CELERYBEAT_USER="avapi"
 CELERYBEAT_GROUP="alienvault"
 
-# /etc/init.d/celerybeat: start and stop the celery periodic task scheduler daemon.
 
-if test -f /etc/default/celeryd; then
-    . /etc/default/celeryd
-fi
-
-if test -f /etc/default/celerybeat; then
-    . /etc/default/celerybeat
-fi
+#CELERY_BIN=${CELERY_BIN:-"celery"}
+CELERY_BIN="/usr/share/python/alienvault-api-core/bin/celery"
+DEFAULT_USER="celery"
+DEFAULT_CELERYBEAT="$CELERY_BIN beat"
 
 CELERYBEAT=${CELERYBEAT:-$DEFAULT_CELERYBEAT}
 CELERYBEAT_LOG_LEVEL=${CELERYBEAT_LOG_LEVEL:-${CELERYBEAT_LOGLEVEL:-$DEFAULT_LOG_LEVEL}}
+
+# Sets --app argument for CELERY_BIN
+CELERY_APP_ARG=""
+if [ ! -z "$CELERY_APP" ]; then
+    CELERY_APP_ARG="--app=$CELERY_APP"
+fi
+
+CELERYBEAT_USER=${CELERYBEAT_USER:-${CELERYD_USER:-$DEFAULT_USER}}
 
 # Set CELERY_CREATE_DIRS to always create log/pid dirs.
 CELERY_CREATE_DIRS=${CELERY_CREATE_DIRS:-0}
@@ -59,22 +149,28 @@ fi
 
 export CELERY_LOADER
 
-CELERYBEAT_OPTS="$CELERYBEAT_OPTS -S celerybeatredis.schedulers.RedisScheduler -f $CELERYBEAT_LOG_FILE -l $CELERYBEAT_LOG_LEVEL --workdir=$DEFAULT_WORKDIR --config=$DEFAULT_CONFIG"
+
+
+CELERYBEAT_OPTS="$CELERYBEAT_OPTS -S celerybeatredis.schedulers.RedisScheduler -f $CELERYBEAT_LOG_FILE --loglevel $CELERYBEAT_LOG_LEVEL --config=$DEFAULT_CONFIG"
+
+if [ -n "$2" ]; then
+    CELERYBEAT_OPTS="$CELERYBEAT_OPTS $2"
+fi
 
 CELERYBEAT_LOG_DIR=`dirname $CELERYBEAT_LOG_FILE`
 CELERYBEAT_PID_DIR=`dirname $CELERYBEAT_PID_FILE`
 
 # Extra start-stop-daemon options, like user/group.
-if [ -n "$CELERYBEAT_USER" ]; then
-    DAEMON_OPTS="$DAEMON_OPTS --uid $CELERYBEAT_USER"
-fi
-if [ -n "$CELERYBEAT_GROUP" ]; then
-    DAEMON_OPTS="$DAEMON_OPTS --gid $CELERYBEAT_GROUP"
+
+#CELERYBEAT_CHDIR=${CELERYBEAT_CHDIR:-$CELERYD_CHDIR}
+CELERYBEAT_CHDIR=$DEFAULT_WORKDIR
+if [ -n "$CELERYBEAT_CHDIR" ]; then
+    DAEMON_OPTS="$DAEMON_OPTS --workdir=$CELERYBEAT_CHDIR"
 fi
 
 
 export PATH="${PATH:+$PATH:}/usr/sbin:/sbin"
-CMD="$CELERYBEAT $CELERYBEAT_OPTS $DAEMON_OPTS --detach --pidfile=$CELERYBEAT_PID_FILE"
+
 check_dev_null() {
     if [ ! -c /dev/null ]; then
         echo "/dev/null is not a character device!"
@@ -110,54 +206,19 @@ create_default_dir() {
     fi
 }
 
-
 check_paths() {
     if [ $CELERY_CREATE_LOGDIR -eq 1 ]; then
         create_default_dir "$CELERYBEAT_LOG_DIR"
     fi
-
     if [ $CELERY_CREATE_RUNDIR -eq 1 ]; then
-        if [ -h $DEFAULT_RUN_DIR ]; then
-            # Wheezy
-            mount | grep "/run type"
-            if [ "$?" != "1" ]; then
-                if [ ! -d $CELERYBEAT_PID_DIR ]; then
-                    create_default_dir "$CELERYBEAT_PID_DIR"
-                fi
-            else
-                log_daemon_msg "ERROR: /run is not mounted yet. The system is not stable. Skipping"
-                exit 1
-            fi
-        else
-            # Squeeze
-            if [ ! -d $CELERYBEAT_PID_DIR ]; then
-                create_default_dir "$CELERYBEAT_PID_DIR"
-            fi
-        fi
+        create_default_dir "$CELERYBEAT_PID_DIR"
     fi
 }
 
 
 create_paths () {
     create_default_dir "$CELERYBEAT_LOG_DIR"
-
-    if [ -h $DEFAULT_RUN_DIR ]; then
-        # Wheezy
-        mount | grep "/run type"
-        if [ "$?" != "1" ]; then
-            if [ ! -d $CELERYBEAT_PID_DIR ]; then
-                create_default_dir "$CELERYBEAT_PID_DIR"
-            fi
-        else
-            log_daemon_msg "ERROR: /run is not mounted yet. The system is not stable. Skipping"
-            exit 1
-        fi
-    else
-        # Squeeze
-        if [ ! -d $CELERYBEAT_PID_DIR ]; then
-            create_default_dir "$CELERYBEAT_PID_DIR"
-        fi
-    fi
+    create_default_dir "$CELERYBEAT_PID_DIR"
 }
 
 
@@ -186,7 +247,7 @@ wait_pid () {
 
 
 stop_beat () {
-    echo -n "Stopping celerybeat... "
+    echo -n "Stopping ${SCRIPT_NAME}... "
     if [ -f "$CELERYBEAT_PID_FILE" ]; then
         wait_pid $(cat "$CELERYBEAT_PID_FILE")
     else
@@ -194,15 +255,46 @@ stop_beat () {
     fi
 }
 
-start_beat () {
-    echo "Starting celerybeat..."
-    if [ -n "$VIRTUALENV" ]; then
-        source $VIRTUALENV/bin/activate
-    fi
-    #echo $CMD
-    $CMD
+_chuid () {
+    su "$CELERYBEAT_USER" -c "$CELERYBEAT $*"
 }
 
+start_beat () {
+    echo "Starting ${SCRIPT_NAME}..."
+    _chuid $CELERY_APP_ARG $CELERYBEAT_OPTS $DAEMON_OPTS --detach \
+                --pidfile="$CELERYBEAT_PID_FILE"
+}
+
+
+check_status () {
+    local failed=
+    local pid_file=$CELERYBEAT_PID_FILE
+    if [ ! -e $pid_file ]; then
+        echo "${SCRIPT_NAME} is down: no pid file found"
+        failed=true
+    elif [ ! -r $pid_file ]; then
+        echo "${SCRIPT_NAME} is in unknown state, user cannot read pid file."
+        failed=true
+    else
+        local pid=`cat "$pid_file"`
+        local cleaned_pid=`echo "$pid" | sed -e 's/[^0-9]//g'`
+        if [ -z "$pid" ] || [ "$cleaned_pid" != "$pid" ]; then
+            echo "${SCRIPT_NAME}: bad pid file ($pid_file)"
+            failed=true
+        else
+            local failed=
+            kill -0 $pid 2> /dev/null || failed=true
+            if [ "$failed" ]; then
+                echo "${SCRIPT_NAME} (pid $pid) is down, but pid file exists!"
+                failed=true
+            else
+                echo "${SCRIPT_NAME} (pid $pid) is up..."
+            fi
+        fi
+    fi
+
+    [ "$failed" ] && exit 1 || exit 0
+}
 
 
 case "$1" in
@@ -217,6 +309,9 @@ case "$1" in
     ;;
     reload|force-reload)
         echo "Use start+stop"
+    ;;
+    status)
+        check_status
     ;;
     restart)
         echo "Restarting celery periodic task scheduler"
@@ -234,7 +329,7 @@ case "$1" in
         check_paths
     ;;
     *)
-        echo "Usage: /etc/init.d/celerybeat {start|stop|restart|create-paths}"
+        echo "Usage: /etc/init.d/${SCRIPT_NAME} {start|stop|restart|create-paths|status}"
         exit 64  # EX_USAGE
     ;;
 esac
diff --git a/os-sim/ossim-mysql/debian/postinst b/os-sim/ossim-mysql/debian/postinst
--- a/os-sim/ossim-mysql/debian/postinst
+++ b/os-sim/ossim-mysql/debian/postinst
@@ -6,33 +6,32 @@ case "$1" in
 	configure)
 
 	if [ ! -f "/etc/ossim/ossim_setup.conf" ]; then
-	      echo "ossim_Setup.conf not found, skip configuration."
-	        exit 0;
-	    fi
+        echo "ossim_Setup.conf not found, skip configuration."
+        exit 0;
+    fi
 
-	prof=`cat /etc/ossim/ossim_setup.conf  | grep -v "profile=server" | grep profile | cut -d= -f2`
-	profiles="$(echo $prof | tr ',' ' ')"
-	SERVER="0"; DATABASE="0"; FRAMEWORK="0"; SENSOR="0"
-	for p in $profiles ; do
-		if [ "$p" = "Server" ]; then SERVER="1"
-		elif [ "$p" = "Database" ]; then DATABASE="1"
-		elif [ "$p" = "Framework" ]; then FRAMEWORK="1"
-		elif [ "$p" = "Sensor" ]; then	SENSOR="1"
-		else
-			echo -e "No profiles found."
-		fi
-	done
+	IS_DATABASE=$(grep -m1 -s -E "^profile=.*(D|d)atabase.*" "$OSSIM_SETUP_CONF_FILE" || true)
 
-## run original update scripts:
+    ## run original update scripts:
 
-# suricata update:
+    # Make sure that MySQL is running
+     if [ ! -z "$IS_DATABASE" ]; then
+	    service mysql status > /dev/null
+        RET=$?
+        if [ $RET -ne 0 ]; then
+            /etc/init.d/mysql start
+        fi
+	fi
+
+
+    # suricata update:
 	srdpi="/var/lib/dpkg/info/suricata-rules-default.postinst"
 	if [ -f "$srdpi" ]; then
 		echo " suricata plugin additional update:"
 		/bin/bash "$srdpi" configure
 	fi
 
-# taxonomy update (includes repriorize):
+    # taxonomy update (includes repriorize):
 	otpi="/var/lib/dpkg/info/ossim-taxonomy.postinst"
 	if [ -f "$otpi" ]; then
 		echo "Taxonomy update:"
